version: '3.9'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - ./gateway/.env
    ports:
      - "8000:8000"
    networks:
      - backend
  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - ./user/.env
    networks:
      - backend
  mail:
    build: ./mail
    restart: always
    hostname: mail
    env_file:
      - ./mail/.env
    networks:
      - backend
  todo:
    build: ./todo
    restart: always
    hostname: todo
    env_file:
      - ./todo/.env
    networks:
      - backend
  team:
    build: ./team
    restart: always
    hostname: team
    env_file:
      - ./team/.env
    networks:
      - backend
networks:
  backend:
    driver: bridge