export enum Pattern {
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGIN = 'USER_LOGIN',
  USER_UPDATE = 'USER_UPDATE',
  USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST',
  USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',
  USER_GRANT_ADMIN = 'USER_GRANT_ADMIN',
  USER_TAKE_ADMIN = 'USER_TAKE_ADMIN',
  USER_BAN_USER = 'USER_BAN_USER',
  USER_VALIDATE_TOKEN = 'USER_VALIDATE_TOKEN',
  USER_GET_USER_BY_ID = 'USER_GET_USER_BY_ID',
}
