export enum Pattern {
  REGISTER = "USER_REGISTER",
  LOGIN = "USER_LOGIN",
  UPDATE = "USER_UPDATE",
  CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD = "USER_CHANGE_PASSWORD",
  GRANT_ADMIN = "USER_GRANT_ADMIN",
  TAKE_ADMIN = "USER_TAKE_ADMIN",
  BAN_USER = "USER_BAN_USER",
  VALIDATE_TOKEN = "USER_VALIDATE_TOKEN",
}
